### ISSUE TITLE
Question: Spark job stuck at Client: Application report for application_1639972759037_0003 (state: ACCEPTED)

### ISSUE THREAD

**Issue by nguacon90** [mohsenasm/spark-on-yarn-cluster#1]
I've run spark job with yarn master, however stuck at state: ACCEPTED.
RM log message: AM container is launched, waiting for AM container to Register with RM
Anyone help?

**Comment by mohsenasm** [comment]
Hi,
Did you follow the readme?
Which one of the readme scenarios, produced this error?

**Comment by nguacon90** [comment]
I only work with your docker-compose.yml and run with simple spark application on yarn mode as code in github: https://github.com/TalentOrigin/source-code/blob/master/sparkcourse/src/main/scala/cloudera/jobs/MySQLSample.scala

The application stuck when initialize spark session.

**Comment by nguacon90** [comment]
Thanks @mohsenasm. I follow the README also start job perfectly.
